version: '3.7'

services:
  internnova-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/usr/src/personalised_nudges
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://username:password@localhost:5432/internnova
      - PROJECT_NAME=InternNova
      - BACKEND_CORS_ORIGINS=["http://localhost:8000", "https://localhost:8000", "http://localhost", "https://localhost"]

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=internnova
    expose: 
      - 5432

volumes:
  postgres_data:
